# Generated by Django 4.2.8 on 2023-12-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill',
            new_name='product',
        ),
    ]
